package com.csvanefalk.keytestgen.core.concurrency.capsules;

import com.csvanefalk.keytestgen.core.classabstraction.KeYJavaMethod;
import com.csvanefalk.keytestgen.core.codecoverage.ICodeCoverageParser;
import com.csvanefalk.keytestgen.core.concurrency.monitor.CaughtException;
import com.csvanefalk.keytestgen.core.concurrency.monitor.ICapsuleMonitor;
import com.csvanefalk.keytestgen.core.concurrency.monitor.IMonitorEvent;
import com.csvanefalk.keytestgen.core.keyinterface.KeYInterface;
import com.csvanefalk.keytestgen.core.model.implementation.Model;
import com.csvanefalk.keytestgen.core.oracle.abstraction.Oracle;
import com.csvanefalk.keytestgen.core.testsuiteabstraction.TestCase;
import com.csvanefalk.keytestgen.core.testsuiteabstraction.TestSuite;
import com.csvanefalk.keytestgen.util.Benchmark;

import de.uka.ilkd.key.java.SourceElement;
import de.uka.ilkd.key.symbolic_execution.model.IExecutionNode;
import de.uka.ilkd.key.symbolic_execution.model.IExecutionStart;
import de.uka.ilkd.key.symbolic_execution.model.IExecutionStatement;

import java.util.LinkedList;
import java.util.List;

/**
 * Instances of this capsule enables KeYTestGen2 to concurrently generate test
 * suites for multiple Java methods.
 *
 * @author christopher
 */
public class MethodCapsule extends AbstractCapsule implements ICapsuleMonitor {

    /**
     * Parser for achieving the desired level of code coverage.
     */
    private final ICodeCoverageParser codeCoverageParser;

    /**
     * Reference to the {@link KeYInterface}, whenever this capsule needs
     * services from the KeY runtime.
     */
    private final KeYInterface keYInterface = KeYInterface.getInstance();

    /**
     * The method which the test suite will be generated for.
     */
    private final KeYJavaMethod targetMethod;

    /**
     * The test suite generated by this capsule
     */
    private TestSuite testSuite = null;

    public MethodCapsule(final ICodeCoverageParser codeCoverageParser, final KeYJavaMethod targetMethod) {
        super();
        this.codeCoverageParser = codeCoverageParser;
        this.targetMethod = targetMethod;
    }

    @Override
    public void doNotify(final ICapsule source, final IMonitorEvent event) {

        /*
         * The signalling capsule caught an exception
         */
        if (event instanceof CaughtException) {

            /*
             * Notify monitors about the exceptioon
             */
            final CaughtException caughtException = (CaughtException) event;
            caughtException.getPayload();
            notifyMonitors(event);

            /*
             * Terminate all children
             */
            source.getController().stopChildren();
        }
    }

    /**
     * Executes the test generation procedure.
     */
    @Override
    public void doWork() {

        /*
         * The generated models.
         */
        final List<Model> models = new LinkedList<Model>();

        /*
         * The oracle for the method which the test cases are being generated
         * for.
         */
        Oracle oracle = null;

        try {

            /*
             * Retrieve the symbolic execution tree for the method, and extract
             * from it the nodes needed in order to reach the desired level of
             * code coverage.
             */
            Benchmark.startBenchmarking("2. [KeY] Create symbolic execution tree");
            final IExecutionStart root = keYInterface.getSymbolicExecutionTree(targetMethod);

            
            //IExecutionStatement s;
            //SourceElement se = s.getActiveStatement();
            System.out.println("number of children:" + root.getChildren().length);
            final List<IExecutionNode> nodes = codeCoverageParser.retrieveNodes(root);

            Benchmark.finishBenchmarking("2. [KeY] Create symbolic execution tree");

            Benchmark.startBenchmarking("3. generating models");

            /*
             * Begin preparing the capsules to be executed
             */
            final CapsuleController<OracleCapsule> oracleController = new CapsuleController<OracleCapsule>();
            final CapsuleController<ModelCapsule> modelController = new CapsuleController<ModelCapsule>();

            /*
             * Setup the model generation capsules for each node.
             */
            for (final IExecutionNode node : nodes) {
                final ModelCapsule modelGenerationCapsule = new ModelCapsule(node);
                modelGenerationCapsule.addMonitor(this);
                modelController.addChild(modelGenerationCapsule);
            }

            /*
             * Setup the Oracle generation capsule for this method
             */
            final OracleCapsule oracleGenerationCapsule = new OracleCapsule(targetMethod);
            oracleController.addChild(oracleGenerationCapsule);

            /*
             * Dispatch and wait for the capsules.
             */
            oracleController.executeAndWait();
            modelController.executeAndWait();

            /*
             * Collect the results
             */
            oracle = oracleGenerationCapsule.getResult();
            for (final ModelCapsule capsule : modelController.getCapsules()) {
                models.add(capsule.getResult());
            }

            /*
             * Construct the test cases.
             */
            final List<TestCase> testCases = new LinkedList<TestCase>();
            for (final Model model : models) {
                final TestCase testCase = TestCase.constructTestCase(targetMethod, model, oracle);
                testCases.add(testCase);
            }
            Benchmark.finishBenchmarking("3. generating models");

            /*
             * Construct the test suite.
             */
            testSuite = TestSuite.constructTestSuite(targetMethod.getDeclaringClass(), targetMethod, testCases);

            /*
             * Finish execution.
             */
            setSucceeded();

        } catch (final Exception e) {
            setThrownException(e);
            notifyMonitors(new CaughtException(e));
            return;
        }

        setSucceeded();
    }

    public TestSuite getResult() {
        return testSuite;
    }
}
