package de.uka.ilkd.key.testgeneration.parser.z3parser.tree.bnf.Absyn; // Java Package generated by the BNF Converter.

public class ENVal extends Val {
  public final Block block_;

  public ENVal(Block p1) { block_ = p1; }

  public <R,A> R accept(de.uka.ilkd.key.testgeneration.parser.z3parser.tree.bnf.Absyn.Val.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof de.uka.ilkd.key.testgeneration.parser.z3parser.tree.bnf.Absyn.ENVal) {
      de.uka.ilkd.key.testgeneration.parser.z3parser.tree.bnf.Absyn.ENVal x = (de.uka.ilkd.key.testgeneration.parser.z3parser.tree.bnf.Absyn.ENVal)o;
      return this.block_.equals(x.block_);
    }
    return false;
  }

  public int hashCode() {
    return this.block_.hashCode();
  }


}
