package de.uka.ilkd.key.testgeneration.parser.z3parser.tree.bnf.Absyn; // Java Package generated by the BNF Converter.

public abstract class Exp implements java.io.Serializable {
  public abstract <R,A> R accept(Exp.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(de.uka.ilkd.key.testgeneration.parser.z3parser.tree.bnf.Absyn.EInt p, A arg);
    public R visit(de.uka.ilkd.key.testgeneration.parser.z3parser.tree.bnf.Absyn.ESInt p, A arg);
    public R visit(de.uka.ilkd.key.testgeneration.parser.z3parser.tree.bnf.Absyn.EBool p, A arg);

  }

}
