package de.uka.ilkd.key.testgeneration.backend;

import de.uka.ilkd.key.testgeneration.core.coreinterface.TestSuite;

/**
 * Implementers of this interface are used in order to convert from the abstract
 * test suites generated by KeYTestGen2 to other formats.
 * 
 * @author christopher
 * 
 */
public interface IFrameworkConverter {

    public String convert(TestSuite testSuite);
}
