/* Generated By:JavaCC: Do not edit this line. SchemaJavaParserConstants.java */
package de.uka.ilkd.key.parser.schemajava;

public interface SchemaJavaParserConstants {

  int EOF = 0;
  int SINGLE_LINE_COMMENT = 9;
  int FORMAL_COMMENT = 10;
  int MULTI_LINE_COMMENT = 11;
  int ABSTRACT = 13;
  int ASSERT = 14;
  int AT = 15;
  int BOOLEAN = 16;
  int BREAK = 17;
  int BIGINT = 18;
  int BYTE = 19;
  int CASE = 20;
  int CATCH = 21;
  int CHAR = 22;
  int CLASS = 23;
  int CONST = 24;
  int CONTINUE = 25;
  int _DEFAULT = 26;
  int DO = 27;
  int DOUBLE = 28;
  int ELSE = 29;
  int ENUM = 30;
  int EXTENDS = 31;
  int FALSE = 32;
  int FINAL = 33;
  int FINALLY = 34;
  int FLOAT = 35;
  int FOR = 36;
  int GHOST = 37;
  int GOTO = 38;
  int IF = 39;
  int IMPLEMENTS = 40;
  int IMPORT = 41;
  int INSTANCEOF = 42;
  int INT = 43;
  int INTERFACE = 44;
  int ISSTATIC = 45;
  int EVALARGS = 46;
  int REPLACEARGS = 47;
  int LONG = 48;
  int NATIVE = 49;
  int NEW = 50;
  int NULL = 51;
  int PACKAGE = 52;
  int PRIVATE = 53;
  int PROTECTED = 54;
  int PUBLIC = 55;
  int RETURN = 56;
  int SHORT = 57;
  int STATIC = 58;
  int SUPER = 59;
  int SWITCH = 60;
  int SYNCHRONIZED = 61;
  int THIS = 62;
  int THROW = 63;
  int THROWS = 64;
  int TRANSACTIONBEGIN = 65;
  int TRANSACTIONCOMMIT = 66;
  int TRANSACTIONFINISH = 67;
  int TRANSACTIONABORT = 68;
  int TRANSIENT = 69;
  int TRUE = 70;
  int TRY = 71;
  int VOID = 72;
  int VOLATILE = 73;
  int WHILE = 74;
  int STRICTFP = 75;
  int CONTEXTSTART = 76;
  int CONTEXTEND = 77;
  int TYPEOF = 78;
  int SWITCHTOIF = 79;
  int UNPACK = 80;
  int SET = 81;
  int INTEGER_LITERAL = 82;
  int DECIMAL_LITERAL = 83;
  int HEX_LITERAL = 84;
  int OCTAL_LITERAL = 85;
  int FLOATING_POINT_LITERAL = 86;
  int EXPONENT = 87;
  int CHARACTER_LITERAL = 88;
  int STRING_LITERAL = 89;
  int IDENTIFIER = 90;
  int LETTER = 91;
  int DIGIT = 92;
  int SVIDENTIFIER = 93;
  int LPAREN = 94;
  int RPAREN = 95;
  int LBRACE = 96;
  int RBRACE = 97;
  int LBRACKET = 98;
  int RBRACKET = 99;
  int SEMICOLON = 100;
  int COMMA = 101;
  int DOT = 102;
  int ASSIGN = 103;
  int LT = 104;
  int BANG = 105;
  int TILDE = 106;
  int HOOK = 107;
  int COLON = 108;
  int EQ = 109;
  int LE = 110;
  int GE = 111;
  int NE = 112;
  int SC_OR = 113;
  int SC_AND = 114;
  int INCR = 115;
  int DECR = 116;
  int PLUS = 117;
  int MINUS = 118;
  int STAR = 119;
  int SLASH = 120;
  int BIT_AND = 121;
  int BIT_OR = 122;
  int XOR = 123;
  int REM = 124;
  int LSHIFT = 125;
  int PLUSASSIGN = 126;
  int MINUSASSIGN = 127;
  int STARASSIGN = 128;
  int SLASHASSIGN = 129;
  int ANDASSIGN = 130;
  int ORASSIGN = 131;
  int XORASSIGN = 132;
  int REMASSIGN = 133;
  int LSHIFTASSIGN = 134;
  int RSIGNEDSHIFTASSIGN = 135;
  int RUNSIGNEDSHIFTASSIGN = 136;
  int SHARP = 137;
  int IMPLICITIDENTIFIER = 138;
  int RUNSIGNEDSHIFT = 139;
  int RSIGNEDSHIFT = 140;
  int GT = 141;

  int DEFAULT = 0;
  int IN_SINGLE_LINE_COMMENT = 1;
  int IN_FORMAL_COMMENT = 2;
  int IN_MULTI_LINE_COMMENT = 3;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"//\"",
    "<token of kind 7>",
    "\"/*\"",
    "<SINGLE_LINE_COMMENT>",
    "\"*/\"",
    "\"*/\"",
    "<token of kind 12>",
    "\"abstract\"",
    "\"assert\"",
    "\"@\"",
    "\"boolean\"",
    "\"break\"",
    "\"\\\\bigint\"",
    "\"byte\"",
    "\"case\"",
    "\"catch\"",
    "\"char\"",
    "\"class\"",
    "\"const\"",
    "\"continue\"",
    "\"default\"",
    "\"do\"",
    "\"double\"",
    "\"else\"",
    "\"enum\"",
    "\"extends\"",
    "\"false\"",
    "\"final\"",
    "\"finally\"",
    "\"float\"",
    "\"for\"",
    "\"ghost\"",
    "\"goto\"",
    "\"if\"",
    "\"implements\"",
    "\"import\"",
    "\"instanceof\"",
    "\"int\"",
    "\"interface\"",
    "\"#isstatic\"",
    "\"#evaluate-arguments\"",
    "\"#replace\"",
    "\"long\"",
    "\"native\"",
    "\"new\"",
    "\"null\"",
    "\"package\"",
    "\"private\"",
    "\"protected\"",
    "\"public\"",
    "\"return\"",
    "\"short\"",
    "\"static\"",
    "\"super\"",
    "\"switch\"",
    "\"synchronized\"",
    "\"this\"",
    "\"throw\"",
    "\"throws\"",
    "\"#beginJavaCardTransaction\"",
    "\"#commitJavaCardTransaction\"",
    "\"#finishJavaCardTransaction\"",
    "\"#abortJavaCardTransaction\"",
    "\"transient\"",
    "\"true\"",
    "\"try\"",
    "\"void\"",
    "\"volatile\"",
    "\"while\"",
    "\"strictfp\"",
    "\"..\"",
    "\"...\"",
    "\"#typeof\"",
    "\"#switch-to-if\"",
    "\"#unpack\"",
    "\"#set\"",
    "<INTEGER_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<HEX_LITERAL>",
    "<OCTAL_LITERAL>",
    "<FLOATING_POINT_LITERAL>",
    "<EXPONENT>",
    "<CHARACTER_LITERAL>",
    "<STRING_LITERAL>",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "<SVIDENTIFIER>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "\"=\"",
    "\"<\"",
    "\"!\"",
    "\"~\"",
    "\"?\"",
    "\":\"",
    "\"==\"",
    "\"<=\"",
    "\">=\"",
    "\"!=\"",
    "\"||\"",
    "\"&&\"",
    "\"++\"",
    "\"--\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"&\"",
    "\"|\"",
    "\"^\"",
    "\"%\"",
    "\"<<\"",
    "\"+=\"",
    "\"-=\"",
    "\"*=\"",
    "\"/=\"",
    "\"&=\"",
    "\"|=\"",
    "\"^=\"",
    "\"%=\"",
    "\"<<=\"",
    "\">>=\"",
    "\">>>=\"",
    "\"#\"",
    "<IMPLICITIDENTIFIER>",
    "\">>>\"",
    "\">>\"",
    "\">\"",
    "\"\\\\seq\"",
    "\"\\\\locset\"",
    "\"\\\\free\"",
    "\"#create-object\"",
    "\"#length-reference\"",
    "\"@(\"",
    "\"#static-evaluate\"",
    "\"method-frame\"",
    "\"#unwind-loop\"",
    "\"#unwind-loop-bounded\"",
    "\"#for-to-while\"",
    "\"#do-break\"",
    "\"#method-call\"",
    "\"#expand-method-body\"",
    "\"#constructor-call\"",
    "\"#special-constructor-call\"",
    "\"#post-work\"",
    "\"#static-initialisation\"",
    "\"#resolve-multiple-var-decl\"",
    "\"#array-post-declaration\"",
    "\"#init-array-creation\"",
    "\"#init-array-creation-transient\"",
    "\"#init-array-assignments\"",
    "\"#enhancedfor-elim\"",
  };

}
