# You can override the included template(s) by including variable overrides
# See https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#priority-of-environment-variables
cache:
  policy: pull-push
  paths:
  - ".gradle/wrapper"
  - ".gradle/caches"
  untracked: true
  key: "${CI_COMMIT_REF_SLUG}"
variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.parallel=true -Dorg.gradle.workers.max=2
    -Dorg.gradle.configureondemand=true"
  GIT_DEPTH: 0
before_script:
- export GRADLE_USER_HOME=`pwd`/.gradle
stages:
- primary
- secondary
- ternary
- test
compile:classes:
  stage: primary
  image: wadoon/key-test-docker:jdk11
  script:
  - javac -version
  - cd key
  - gradle --build-cache classes
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
    - build
    - ".gradle"
compile:testClasses:
  dependencies:
  - compile:classes
  stage: secondary
  image: wadoon/key-test-docker:jdk11
  script:
  - javac -version
  - cd key
  - gradle --build-cache --parallel testClasses
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull-push
    paths:
    - build
    - ".gradle"
compile:testClasses8:
  dependencies: []
  stage: secondary
  image: wadoon/key-test-docker:jdk8
  script:
  - javac -version
  - cd key
  - gradle --parallel classes testClasses
sonarqube:
  dependencies:
  - compile:testClasses
  stage: ternary
  image: wadoon/key-test-docker:jdk11
  allow_failure: true
  script:
  - cd key
  - gradle --build-cache --continue -Dsonar.qualitygate.wait=true -DjacocoEnabled=true
    testFast sonarqube
  - "./scripts/tools/sonarqube_hint.py"
  only:
  - merge_requests
  - master
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
    - build
    - ".gradle"
  artifacts:
    reports:
      junit:
      - "**/**/build/test-results/*/TEST-*.xml"
checkstyle:
  stage: primary
  image: wadoon/key-test-docker:jdk11
  allow_failure: true
  script:
  - "(key/scripts/tools/checkstyle/runIncrementalCheckstyle.sh | tee report.txt) ||
    true"
  - key/scripts/tools/checkstyle/translateAudit.py report.txt > report.json
  artifacts:
    name: checkstyle-report-$CI_JOB_ID
    paths:
    - report.txt
    when: always
    reports:
      codequality: report.json
    expire_in: 1 year
sast:
  stage: test
include:
- template: Security/SAST.gitlab-ci.yml
