#
# This files describes the workflow of the continous integration
# checker for KeY run within gitlab.
#
# Jenkins runs are triggered from somewhere else.
#

image: wadoon/key-test-docker:jdk11

cache:
  policy: pull-push
  paths:
    - .gradle/wrapper
    - .gradle/caches
    - key/**/build/
  untracked: true
  key: $CI_COMMIT_REF_NAME

variables:
  GRADLE_OPTS:  "-Dorg.gradle.daemon=false -Dorg.gradle.parallel=true -Dorg.gradle.workers.max=2 -Dorg.gradle.configureondemand=true"
  GIT_DEPTH: 0
  SONAR_SCANNER_OPTS: -Xmx8G
  TIMEOUT_SECONDS: 36000


before_script:
  #  - echo `pwd` # debug
  #  - echo "$CI_BUILD_NAME, $CI_BUILD_REF_NAME $CI_BUILD_STAGE" # debug
  - export GRADLE_USER_HOME=`pwd`/.gradle
  - export SONAR_SCANNER_OPTS="-Xmx8G"

stages:
    - primary
    - secondary
    - deploy
    - test

compile:classes:
  stage: primary
  image: wadoon/key-test-docker:jdk11
  script:
    - javac -version
    - cd key
    - gradle --build-cache classes

compile:testClasses:
  dependencies: [ "compile:classes" ]
  stage: secondary
  image: wadoon/key-test-docker:jdk11
  script:
    - javac -version
    - cd key
    - gradle --build-cache --parallel testClasses


test:
  stage: test
  script:
    - cd key
    - gradle --build-cache --continue testAggregateTestReport -x key.core.proof_references:test -x key.core.symbolic_execution:test
  artifacts:
    when: always
    paths:
      - key/key.ui/build/reports/tests/unit-test/
    expire_in: 1 month
    reports:
      junit:
        - "**/**/build/test-results/test/TEST-*.xml"

code_intelligence_java:
  stage: primary
  needs: []
  allow_failure: true
  rules:
    - if: $CODE_INTELLIGENCE_DISABLED
      when: never
#    - if: $CI_COMMIT_BRANCH
#      exists:
#        - '**/*.java'
  script:
    - cd key
    - curl -fLo coursier https://git.io/coursier-cli
    - chmod +x coursier
    - ./coursier launch com.sourcegraph:scip-java_2.13:0.8.8 -- index
    - ls
    - cat index.scip
  artifacts:
    reports:
      lsif: index.scip

include:
  - template: Security/License-Scanning.gitlab-ci.yml
  - template: Security/SAST.gitlab-ci.yml

license_scanning:
  variables:
    CI_DEBUG_TRACE: "true"



#include:
#  - template: Code-Quality.gitlab-ci.yml

#code_quality:
#  services:            # Shut off Docker-in-Docker
#  tags:
#    - dind     # Set this job to only run on our new specialized runner

my_code_quality:
  script:
    - cd key
    - gradle --build-cache --continue pmdMain
    - wget https://repo1.maven.org/maven2/se/bjurr/violations/violations-command-line/1.22.3/violations-command-line-1.22.3.jar -O violations-command-line-1.22.3.jar
    - java -jar violations-command-line-1.22.3.jar -cc code-climate-report.json -v PMD . ".*/pmd/main\.xml$" "PMD" | wc -l
    - ls
  artifacts:
    reports:
      codequality: key/code-climate-report.json
    expire_in: 1 week

    # -v "CHECKSTYLE" "." ".*checkstyle/main\.xml$" "Checkstyle"




sast:
  stage: test



deploy-nightly:
  stage: deploy
  script:
    - cd key
    - BUILD_NUMBER=SNAPSHOT gradle publish
  only:
    - stable

deploy-release:
  when: manual
  stage: deploy
  script:
    - cd key
    - gradle publish
  only:
    - /^KeY-.*$/
