#!/bin/sh

# Going into key/key/scripts folder, rely on BASH
# see http://mywiki.wooledge.org/BashFAQ/028
cd "${BASH_SOURCE%/*}/" || exit

UNAME=$(uname -s 2>/dev/null | tr '[:upper:]' '[:lower:]')
ARCH=$(uname -pm 2>/dev/null | tr '[:upper:]' '[:lower:]' | tr ' ' '-')

if [ -z "$JAVA_HOME" ] ; then
    JAVA=`which java`
    if [ -z "$JAVA" ] ; then
	echo "Cannot find java executable. Please set your \$PATH or \$JAVA_HOME."
	exit 1
    fi
else
    echo "Using JDK installation from:      $JAVA_HOME"
    if [ "$UNAME" = "darwin" ] ; then
	JRE=$JAVA_HOME/Home
	JAVA=$JRE/bin/java
        # other OS
    else
	JRE=$JAVA_HOME
	JAVA=$JRE/bin/java
    fi
fi

[ ! -x  $JAVA ] && \
    (echo "The determined java executable '$JAVA' is not executable or exists"; exit 1)

#
# $KEY_HOME
#
KEY_HOME=${KEY_HOME:-$(readlink -f $(pwd)/..)}
echo "Using KeY installation from: $KEY_HOME"

START_SCRIPT=$KEY_HOME/key.ui/build/install/key.ui/bin/key.ui

if [ ! -f $START_SCRIPT ]; then
    GRADLE=$(which gradle)
    GRADLE=${GRADLE:-"./gradlew"}

    echo "$START_SCRIPT does not exists."
    read -r -p "Should I create it with '$GRADLE :key.ui:installDist'? [y/N]} " response
    case "$response" in
        [yY][eE][sS]|[yY])
            cd $KEY_HOME
            $GRADLE --parallel :key.ui:installDist || exit
            ;;
        *)
            false
            ;;
    esac
fi

if [ -f $START_SCRIPT ]; then
    $START_SCRIPT $@
else
    echo "For the second time, $START_SCRIPT does not exists."
fi
