
//----------------------------------------------------
// The following code was generated by CUP v0.12joho 20110608
// Fri Jan 18 23:23:39 CET 2013
//----------------------------------------------------

package de.uni_freiburg.informatik.ultimate.smtinterpol.smtlib2;

/** CUP generated class containing symbol constants. */
public class LexerSymbols {
  /* terminals */
  public static final int error = 0;
  public static final int EOF = 1;
  public static final int UNDERSCORE = 2;
  public static final int BANG = 3;
  public static final int AS = 4;
  public static final int ASSERT = 5;
  public static final int CHECKSAT = 6;
  public static final int CONTINUEDEXECUTION = 7;
  public static final int DECLARESORT = 8;
  public static final int DECLAREFUN = 9;
  public static final int DEFINESORT = 10;
  public static final int DEFINEFUN = 11;
  public static final int ERRORSYM = 12;
  public static final int EXISTS = 13;
  public static final int EXIT = 14;
  public static final int FALSE = 15;
  public static final int FORALL = 16;
  public static final int GETASSERTIONS = 17;
  public static final int GETASSIGNMENT = 18;
  public static final int GETINFO = 19;
  public static final int GETINTERPOLANTS = 20;
  public static final int GETMODEL = 21;
  public static final int GETOPTION = 22;
  public static final int GETPROOF = 23;
  public static final int GETUNSATCORE = 24;
  public static final int GETVALUE = 25;
  public static final int IMMEDIATEEXIT = 26;
  public static final int INCOMPLETE = 27;
  public static final int LET = 28;
  public static final int LOGIC = 29;
  public static final int NONE = 30;
  public static final int NUMERALSYM = 31;
  public static final int MEMOUT = 32;
  public static final int PAR = 33;
  public static final int POP = 34;
  public static final int PUSH = 35;
  public static final int DECIMALSYM = 36;
  public static final int SAT = 37;
  public static final int SUCCESS = 38;
  public static final int SETLOGIC = 39;
  public static final int SETINFO = 40;
  public static final int SETOPTION = 41;
  public static final int STRINGSYM = 42;
  public static final int THEORY = 43;
  public static final int TRUE = 44;
  public static final int UNKNOWN = 45;
  public static final int UNSUPPORTED = 46;
  public static final int UNSAT = 47;
  public static final int INCLUDE = 48;
  public static final int RESET = 49;
  public static final int SIMPLIFY = 50;
  public static final int TIMED = 51;
  public static final int CNAMED = 52;
  public static final int CPATTERN = 53;
  public static final int CSORTSDESCRIPTION = 54;
  public static final int CSORTS = 55;
  public static final int CFUNS = 56;
  public static final int CFUNSDESCRIPTION = 57;
  public static final int CDEFINITION = 58;
  public static final int CEXTENSIONS = 59;
  public static final int CLANGUAGE = 60;
  public static final int CTHEORIES = 61;
  public static final int CNOTES = 62;
  public static final int CVALUES = 63;
  public static final int CDIAGNOSTICOUTPUTCHANNEL = 64;
  public static final int CREGULAROUTPUTCHANNEL = 65;
  public static final int CEXPANDDEFINITIONS = 66;
  public static final int CINTERACTIVEMODE = 67;
  public static final int CPRINTSUCCESS = 68;
  public static final int CVERBOSITY = 69;
  public static final int CPRODUCEASSIGNMENTS = 70;
  public static final int CPRODUCEMODELS = 71;
  public static final int CPRODUCEPROOFS = 72;
  public static final int CPRODUCEUNSATCORES = 73;
  public static final int CRANDOMSEED = 74;
  public static final int CINTERPOLANTCHECKMODE = 75;
  public static final int CSTRONGSIMPLIFIER = 76;
  public static final int CTIMEOUT = 77;
  public static final int SYMBOL = 78;
  public static final int KEYWORD = 79;
  public static final int NUMERAL = 80;
  public static final int DECIMAL = 81;
  public static final int HEXADECIMAL = 82;
  public static final int BINARY = 83;
  public static final int STRING = 84;
  public static final int LPAR = 85;
  public static final int RPAR = 86;
}

