package de.uka.ilkd.key.testgeneration.xmlparser.junitparser;

import java.io.ByteArrayInputStream;
import java.io.InputStream;
import java.util.LinkedList;
import java.util.List;

import javax.xml.stream.XMLEventReader;
import javax.xml.stream.XMLInputFactory;
import javax.xml.stream.XMLStreamException;
import javax.xml.stream.events.XMLEvent;

import de.uka.ilkd.key.testgeneration.XMLHandler;
import de.uka.ilkd.key.testgeneration.xmlparser.ITestCaseParser;
import de.uka.ilkd.key.testgeneration.xmlparser.XMLParserException;

/**
 * Instances of this class are used in order to create JUnit4 test suites from the internal XML
 * representation generated by KeYTestGen2.
 * 
 * @author christopher
 */
public class JUnitParser
        extends XMLHandler
        implements ITestCaseParser<String> {

    /**
     * The singleton instance of this class. Lazily instantiated.
     */
    private static JUnitParser instance;

    private JUnitParser() {

    }

    /**
     * @return the singleton instance of this class.
     */
    public static JUnitParser getInstance() {

        if (instance == null) {
            instance = new JUnitParser();
        }
        return instance;
    }

    /**
     * Create a set of Test classes from an XML test suite.
     * 
     * @throws XMLParserException
     */
    @Override
    public String generateTestCaseFromXML(String representation)
            throws XMLParserException {

        try {

            JUnitMediator result =
                    new JUnitGenerationWorker(representation).generateJUnitTestSuite();

            return null;
        }
        catch (XMLStreamException xme) {
            throw new XMLParserException(xme.getMessage());
        }
    }

    /**
     * Worker class which processes an XML document in order to produce a concrete JUnit test suite.
     * 
     * @author christopher
     */
    private static class JUnitGenerationWorker {

        /**
         * Used for creating XML related utility classes.
         */
        XMLInputFactory inputFactory = XMLInputFactory.newInstance();

        /**
         * The stream from the target XML document.
         */
        private InputStream inputStream;

        /**
         * Used for parsing {@link XMLEvent} instances from the XML document.
         */
        XMLEventReader eventReader;

        public JUnitGenerationWorker(String xmlDocument) throws XMLStreamException {

            inputStream = new ByteArrayInputStream(xmlDocument.getBytes());
            eventReader = inputFactory.createXMLEventReader(inputStream);
        }

        public JUnitMediator generateJUnitTestSuite() throws XMLStreamException {

            /*
             * The main parse loop. Identify the nature of each XML element, and process the tree
             * accordingly.
             */
            while (eventReader.hasNext()) {

                XMLEvent event = eventReader.nextTag();

                if (event.isStartElement()) {
                    if (getEventName(event).equals(TESTCASE_ROOT)) {
                        System.out.println(event);
                    }
                }
            }
            return null;
        }

        /**
         * Processes an XML subtree corresponding to a test case.
         * 
         * @param inputStream
         *            the {@link InputStream} for this session
         * @param eventReader
         *            the {@link XMLEventReader} for this session
         */
        private void processTestCase(InputStream inputStream, XMLEventReader eventReader) {

        }

        private String getEventName(XMLEvent event) {

            if (event.isStartElement()) {
                return event.asStartElement().getName().getLocalPart();
            }

            if (event.isEndElement()) {
                return event.asEndElement().getName().getLocalPart();
            }

            return "";
        }
    }

    /**
     * Mediating class which encapsulates JUnit data generated during the parsing of an XML test
     * suite.
     * 
     * @author christopher
     */
    private static class JUnitMediator {

        private final List<String> imports = new LinkedList<String>();

        public void addImport(String importString) {

            imports.add(importString);
        }

        /**
         * @return the imports
         */
        public List<String> getImports() {

            return imports;
        }
    }
}