
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Oct 12 19:44:47 CEST 2012
//----------------------------------------------------

package de.uka.ilkd.key.testgeneration.parser.z3parser.tree.bnf;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int _SYMB_8 = 10;
  public static final int _SYMB_7 = 9;
  public static final int _SYMB_6 = 8;
  public static final int _SYMB_5 = 7;
  public static final int _SYMB_4 = 6;
  public static final int _SYMB_3 = 5;
  public static final int _SYMB_2 = 4;
  public static final int _SYMB_1 = 3;
  public static final int _SYMB_0 = 2;
  public static final int EOF = 0;
  public static final int _IDENT_ = 13;
  public static final int error = 1;
  public static final int _INTEGER_ = 12;
  public static final int _SYMB_9 = 11;
}

