/* Generated By:JavaCC: Do not edit this line. JavaCCParserConstants.java */
package recoder.parser;

public interface JavaCCParserConstants {

  int EOF = 0;
  int SINGLE_LINE_COMMENT = 9;
  int FORMAL_COMMENT = 10;
  int MULTI_LINE_COMMENT = 11;
  int ABSTRACT = 13;
  int ASSERT = 14;
  int AT = 15;
  int BOOLEAN = 16;
  int BREAK = 17;
  int BYTE = 18;
  int CASE = 19;
  int CATCH = 20;
  int CHAR = 21;
  int CLASS = 22;
  int CONST = 23;
  int CONTINUE = 24;
  int _DEFAULT = 25;
  int DO = 26;
  int DOUBLE = 27;
  int ELSE = 28;
  int ENUM = 29;
  int EXTENDS = 30;
  int FALSE = 31;
  int FINAL = 32;
  int FINALLY = 33;
  int FLOAT = 34;
  int FOR = 35;
  int GOTO = 36;
  int IF = 37;
  int IMPLEMENTS = 38;
  int IMPORT = 39;
  int INSTANCEOF = 40;
  int INT = 41;
  int INTERFACE = 42;
  int LONG = 43;
  int NATIVE = 44;
  int NEW = 45;
  int NULL = 46;
  int PACKAGE = 47;
  int PRIVATE = 48;
  int PROTECTED = 49;
  int PUBLIC = 50;
  int RETURN = 51;
  int SHORT = 52;
  int STATIC = 53;
  int SUPER = 54;
  int SWITCH = 55;
  int SYNCHRONIZED = 56;
  int THIS = 57;
  int THROW = 58;
  int THROWS = 59;
  int TRANSIENT = 60;
  int TRUE = 61;
  int TRY = 62;
  int VOID = 63;
  int VOLATILE = 64;
  int WHILE = 65;
  int VARARGDENOTER = 66;
  int STRICTFP = 67;
  int LONG_LITERAL = 68;
  int INTEGER_LITERAL = 69;
  int DECIMAL_LITERAL = 70;
  int HEX_LITERAL = 71;
  int OCTAL_LITERAL = 72;
  int FLOATING_POINT_LITERAL = 73;
  int DECIMAL_FLOATING_POINT_LITERAL = 74;
  int DECIMAL_EXPONENT = 75;
  int HEXADECIMAL_FLOATING_POINT_LITERAL = 76;
  int HEXADECIMAL_EXPONENT = 77;
  int CHARACTER_LITERAL = 78;
  int STRING_LITERAL = 79;
  int IDENTIFIER = 80;
  int LETTER = 81;
  int PART_LETTER = 82;
  int LPAREN = 83;
  int RPAREN = 84;
  int LBRACE = 85;
  int RBRACE = 86;
  int LBRACKET = 87;
  int RBRACKET = 88;
  int SEMICOLON = 89;
  int COMMA = 90;
  int DOT = 91;
  int ASSIGN = 92;
  int LT = 93;
  int BANG = 94;
  int TILDE = 95;
  int HOOK = 96;
  int COLON = 97;
  int EQ = 98;
  int LE = 99;
  int GE = 100;
  int NE = 101;
  int SC_OR = 102;
  int SC_AND = 103;
  int INCR = 104;
  int DECR = 105;
  int PLUS = 106;
  int MINUS = 107;
  int STAR = 108;
  int SLASH = 109;
  int BIT_AND = 110;
  int BIT_OR = 111;
  int XOR = 112;
  int REM = 113;
  int LSHIFT = 114;
  int PLUSASSIGN = 115;
  int MINUSASSIGN = 116;
  int STARASSIGN = 117;
  int SLASHASSIGN = 118;
  int ANDASSIGN = 119;
  int ORASSIGN = 120;
  int XORASSIGN = 121;
  int REMASSIGN = 122;
  int LSHIFTASSIGN = 123;
  int RSIGNEDSHIFTASSIGN = 124;
  int RUNSIGNEDSHIFTASSIGN = 125;
  int RUNSIGNEDSHIFT = 126;
  int RSIGNEDSHIFT = 127;
  int GT = 128;

  int DEFAULT = 0;
  int IN_SINGLE_LINE_COMMENT = 1;
  int IN_FORMAL_COMMENT = 2;
  int IN_MULTI_LINE_COMMENT = 3;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"//\"",
    "<token of kind 7>",
    "\"/*\"",
    "<SINGLE_LINE_COMMENT>",
    "\"*/\"",
    "\"*/\"",
    "<token of kind 12>",
    "\"abstract\"",
    "\"assert\"",
    "\"@\"",
    "\"boolean\"",
    "\"break\"",
    "\"byte\"",
    "\"case\"",
    "\"catch\"",
    "\"char\"",
    "\"class\"",
    "\"const\"",
    "\"continue\"",
    "\"default\"",
    "\"do\"",
    "\"double\"",
    "\"else\"",
    "\"enum\"",
    "\"extends\"",
    "\"false\"",
    "\"final\"",
    "\"finally\"",
    "\"float\"",
    "\"for\"",
    "\"goto\"",
    "\"if\"",
    "\"implements\"",
    "\"import\"",
    "\"instanceof\"",
    "\"int\"",
    "\"interface\"",
    "\"long\"",
    "\"native\"",
    "\"new\"",
    "\"null\"",
    "\"package\"",
    "\"private\"",
    "\"protected\"",
    "\"public\"",
    "\"return\"",
    "\"short\"",
    "\"static\"",
    "\"super\"",
    "\"switch\"",
    "\"synchronized\"",
    "\"this\"",
    "\"throw\"",
    "\"throws\"",
    "\"transient\"",
    "\"true\"",
    "\"try\"",
    "\"void\"",
    "\"volatile\"",
    "\"while\"",
    "\"...\"",
    "\"strictfp\"",
    "<LONG_LITERAL>",
    "<INTEGER_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<HEX_LITERAL>",
    "<OCTAL_LITERAL>",
    "<FLOATING_POINT_LITERAL>",
    "<DECIMAL_FLOATING_POINT_LITERAL>",
    "<DECIMAL_EXPONENT>",
    "<HEXADECIMAL_FLOATING_POINT_LITERAL>",
    "<HEXADECIMAL_EXPONENT>",
    "<CHARACTER_LITERAL>",
    "<STRING_LITERAL>",
    "<IDENTIFIER>",
    "<LETTER>",
    "<PART_LETTER>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "\"=\"",
    "\"<\"",
    "\"!\"",
    "\"~\"",
    "\"?\"",
    "\":\"",
    "\"==\"",
    "\"<=\"",
    "\">=\"",
    "\"!=\"",
    "\"||\"",
    "\"&&\"",
    "\"++\"",
    "\"--\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"&\"",
    "\"|\"",
    "\"^\"",
    "\"%\"",
    "\"<<\"",
    "\"+=\"",
    "\"-=\"",
    "\"*=\"",
    "\"/=\"",
    "\"&=\"",
    "\"|=\"",
    "\"^=\"",
    "\"%=\"",
    "\"<<=\"",
    "\">>=\"",
    "\">>>=\"",
    "\">>>\"",
    "\">>\"",
    "\">\"",
  };

}
