/* Generated By:JavaCC: Do not edit this line. ProofJavaParserConstants.java */
package de.uka.ilkd.key.parser.proofjava;

public interface ProofJavaParserConstants {

  int EOF = 0;
  int SINGLE_LINE_COMMENT = 9;
  int FORMAL_COMMENT = 10;
  int MULTI_LINE_COMMENT = 11;
  int ABSTRACT = 13;
  int ASSERT = 14;
  int AT = 15;
  int BIGINT = 16;
  int BOOLEAN = 17;
  int BREAK = 18;
  int BYTE = 19;
  int CASE = 20;
  int CATCH = 21;
  int CHAR = 22;
  int CLASS = 23;
  int CONST = 24;
  int CONTINUE = 25;
  int _DEFAULT = 26;
  int DO = 27;
  int DOUBLE = 28;
  int ELSE = 29;
  int ENUM = 30;
  int EXTENDS = 31;
  int FALSE = 32;
  int FINAL = 33;
  int FINALLY = 34;
  int FLOAT = 35;
  int FOR = 36;
  int FREE = 37;
  int GOTO = 38;
  int IF = 39;
  int IMPLEMENTS = 40;
  int IMPORT = 41;
  int INSTANCEOF = 42;
  int INT = 43;
  int INTERFACE = 44;
  int LOCSET = 45;
  int LONG = 46;
  int METHODFRAME = 47;
  int NATIVE = 48;
  int NEW = 49;
  int NULL = 50;
  int PACKAGE = 51;
  int PRIVATE = 52;
  int PROTECTED = 53;
  int PUBLIC = 54;
  int RETURN = 55;
  int SEQ = 56;
  int SET = 57;
  int SHORT = 58;
  int STATIC = 59;
  int SUPER = 60;
  int SWITCH = 61;
  int SYNCHRONIZED = 62;
  int THIS = 63;
  int THROW = 64;
  int THROWS = 65;
  int TRANSACTIONBEGIN = 66;
  int TRANSACTIONCOMMIT = 67;
  int TRANSACTIONFINISH = 68;
  int TRANSACTIONABORT = 69;
  int TRANSIENT = 70;
  int TRUE = 71;
  int TRY = 72;
  int VOID = 73;
  int VOLATILE = 74;
  int WHILE = 75;
  int VARARGDENOTER = 76;
  int STRICTFP = 77;
  int INTEGER_LITERAL = 78;
  int DECIMAL_LITERAL = 79;
  int HEX_LITERAL = 80;
  int OCTAL_LITERAL = 81;
  int FLOATING_POINT_LITERAL = 82;
  int EXPONENT = 83;
  int CHARACTER_LITERAL = 84;
  int STRING_LITERAL = 85;
  int IDENTIFIER = 86;
  int LETTER = 87;
  int DIGIT = 88;
  int DL_EMBEDDED_FUNCTION = 89;
  int LPAREN = 90;
  int RPAREN = 91;
  int LBRACE = 92;
  int RBRACE = 93;
  int LBRACKET = 94;
  int RBRACKET = 95;
  int SEMICOLON = 96;
  int COMMA = 97;
  int DOT = 98;
  int ASSIGN = 99;
  int BANG = 100;
  int TILDE = 101;
  int HOOK = 102;
  int COLON = 103;
  int DOUBLECOLON = 104;
  int EQ = 105;
  int LE = 106;
  int GE = 107;
  int NE = 108;
  int SC_OR = 109;
  int SC_AND = 110;
  int INCR = 111;
  int DECR = 112;
  int PLUS = 113;
  int MINUS = 114;
  int STAR = 115;
  int SLASH = 116;
  int BIT_AND = 117;
  int BIT_OR = 118;
  int XOR = 119;
  int REM = 120;
  int LSHIFT = 121;
  int PLUSASSIGN = 122;
  int MINUSASSIGN = 123;
  int STARASSIGN = 124;
  int SLASHASSIGN = 125;
  int ANDASSIGN = 126;
  int ORASSIGN = 127;
  int XORASSIGN = 128;
  int REMASSIGN = 129;
  int LSHIFTASSIGN = 130;
  int RSIGNEDSHIFTASSIGN = 131;
  int RUNSIGNEDSHIFTASSIGN = 132;
  int SHARP = 133;
  int RUNSIGNEDSHIFT = 134;
  int RSIGNEDSHIFT = 135;
  int GT = 136;
  int IMPLICITIDENTIFIER = 137;
  int LT = 138;
  int UNICODE_BYTE_ORDER_MARKER = 139;
  int UNKNOWN_CHARACTER_SEQUENCE = 140;

  int DEFAULT = 0;
  int IN_SINGLE_LINE_COMMENT = 1;
  int IN_FORMAL_COMMENT = 2;
  int IN_MULTI_LINE_COMMENT = 3;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"//\"",
    "<token of kind 7>",
    "\"/*\"",
    "<SINGLE_LINE_COMMENT>",
    "\"*/\"",
    "\"*/\"",
    "<token of kind 12>",
    "\"abstract\"",
    "\"assert\"",
    "\"@\"",
    "\"\\\\bigint\"",
    "\"boolean\"",
    "\"break\"",
    "\"byte\"",
    "\"case\"",
    "\"catch\"",
    "\"char\"",
    "\"class\"",
    "\"const\"",
    "\"continue\"",
    "\"default\"",
    "\"do\"",
    "\"double\"",
    "\"else\"",
    "\"enum\"",
    "\"extends\"",
    "\"false\"",
    "\"final\"",
    "\"finally\"",
    "\"float\"",
    "\"for\"",
    "\"\\\\free\"",
    "\"goto\"",
    "\"if\"",
    "\"implements\"",
    "\"import\"",
    "\"instanceof\"",
    "\"int\"",
    "\"interface\"",
    "\"\\\\locset\"",
    "\"long\"",
    "\"method-frame\"",
    "\"native\"",
    "\"new\"",
    "\"null\"",
    "\"package\"",
    "\"private\"",
    "\"protected\"",
    "\"public\"",
    "\"return\"",
    "\"\\\\seq\"",
    "\"\\\\set\"",
    "\"short\"",
    "\"static\"",
    "\"super\"",
    "\"switch\"",
    "\"synchronized\"",
    "\"this\"",
    "\"throw\"",
    "\"throws\"",
    "\"#beginJavaCardTransaction\"",
    "\"#commitJavaCardTransaction\"",
    "\"#finishJavaCardTransaction\"",
    "\"#abortJavaCardTransaction\"",
    "\"transient\"",
    "\"true\"",
    "\"try\"",
    "\"void\"",
    "\"volatile\"",
    "\"while\"",
    "\"...\"",
    "\"strictfp\"",
    "<INTEGER_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<HEX_LITERAL>",
    "<OCTAL_LITERAL>",
    "<FLOATING_POINT_LITERAL>",
    "<EXPONENT>",
    "<CHARACTER_LITERAL>",
    "<STRING_LITERAL>",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "<DL_EMBEDDED_FUNCTION>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "\"=\"",
    "\"!\"",
    "\"~\"",
    "\"?\"",
    "\":\"",
    "\"::\"",
    "\"==\"",
    "\"<=\"",
    "\">=\"",
    "\"!=\"",
    "\"||\"",
    "\"&&\"",
    "\"++\"",
    "\"--\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"&\"",
    "\"|\"",
    "\"^\"",
    "\"%\"",
    "\"<<\"",
    "\"+=\"",
    "\"-=\"",
    "\"*=\"",
    "\"/=\"",
    "\"&=\"",
    "\"|=\"",
    "\"^=\"",
    "\"%=\"",
    "\"<<=\"",
    "\">>=\"",
    "\">>>=\"",
    "\"#\"",
    "\">>>\"",
    "\">>\"",
    "\">\"",
    "<IMPLICITIDENTIFIER>",
    "\"<\"",
    "\"\\ufeff\"",
    "<UNKNOWN_CHARACTER_SEQUENCE>",
    "\"\\\\indexOf\"",
    "\"\\\\seq_length\"",
    "\"\\\\seq_get\"",
    "\"@(\"",
    "\"\\\\singleton\"",
    "\"\\\\set_union\"",
    "\"\\\\intersect\"",
    "\"\\\\set_minus\"",
    "\"\\\\all_fields\"",
    "\"\\\\all_objects\"",
    "\"\\\\seq_singleton\"",
    "\"\\\\seq_concat\"",
    "\"\\\\seq_sub\"",
    "\"\\\\seq_reverse\"",
    "\"\\\\seq_put\"",
    "\"..\"",
    "\"\\\\empty\"",
    "\"\\\\seq_empty\"",
    "\"#catchAll\"",
    "\"result->\"",
    "\"source=\"",
    "\",this=\"",
  };

}
