/* This file has been generated by Stubmaker (de.uka.ilkd.stubmaker)
 * Date: Fri Jul 11 11:49:17 CEST 2014
 */
package java.lang;

public class IllegalThreadStateException extends java.lang.IllegalArgumentException
{

   public IllegalThreadStateException(){};
   public IllegalThreadStateException(java.lang.String s){super(s);}
}
