/* This file has been generated by Stubmaker (de.uka.ilkd.stubmaker)
 * Date: Fri Jul 11 11:49:17 CEST 2014
 */
package java.lang;

public class Thread extends java.lang.Object implements java.lang.Runnable
{
   public final static int MIN_PRIORITY = 1;
   public final static int NORM_PRIORITY = 5;
   public final static int MAX_PRIORITY = 10;

   public static java.lang.Thread currentThread();
   public static void yield();
   public static void sleep(long arg0) throws java.lang.InterruptedException;
   public static void sleep(long millis, int superThis1) throws java.lang.InterruptedException;
   protected java.lang.Object clone() throws java.lang.CloneNotSupportedException;
   public Thread();
   public Thread(java.lang.Runnable target);
   public Thread(java.lang.String name);
   public Thread(java.lang.Runnable target, java.lang.String name);
   public void start();
   public void run();
   public final void stop();
   public final void stop(java.lang.Throwable obj);
   public void interrupt();
   public static boolean interrupted();
   public boolean isInterrupted();
   public void destroy();
   public final boolean isAlive();
   public final void suspend();
   public final void resume();
   public final void setPriority(int newPriority);
   public final int getPriority();
   public final void setName(java.lang.String name);
   public final java.lang.String getName();
   public static int activeCount();
   public static int enumerate(java.lang.Thread[] tarray);
   public int countStackFrames();
   public final void join(long millis) throws java.lang.InterruptedException;
   public final void join(long millis, int superThis1) throws java.lang.InterruptedException;
   public final void join() throws java.lang.InterruptedException;
   public static void dumpStack();
   public final void setDaemon(boolean on);
   public final boolean isDaemon();
   public final void checkAccess();
   public java.lang.String toString();
   public static boolean holdsLock(java.lang.Object arg0);
   public static java.util.Map getAllStackTraces();
   public long getId();
}
