package com.csvanefalk.keytestgen.backend.custom;

/**
 * Classes implementing this interface are capable of producing concrete test
 * suites based on XML representations generated by KeYTestGen2. The test suites
 * will be returned as instances of type T, allowing implementors to be flexible
 * with how they wish to produce their test suites.
 *
 * @author christopher
 */
public interface ITestCaseParser<T> {

    public T generateTestCaseFromXML(String representation)
            throws XMLParserException;
}
