/** This is a test driver generated by KeY 2.7 (internal: 90bb886cd7b78027c8f6703803461f09e5699bb9) (www.key-project.org). 
 * Possible use cases:
 *  Use Case 1. Using JUnit 4:
 *        javac -cp .:PATH_TO_JUNIT4_JAR *.java
 *        java  -cp .:PATH_TO_JUNIT4_JAR:PATH_TO_HAMCREST_JAR org.junit.runner.JUnitCore GeneratedTest
 *  Use Case 2. Use JML runtime checker: 
 *      Compile this file and and execute the main method with a JML runtime checker. On linux you can use the built-in scripts:
 *        ./compileWithOpenJML.sh
 *        ./executeWithOpenJML.sh GeneratedTest
 *  Use Case 3. Use simply a program debugger to follow and understand the execution of the program.
 * @author Christoph Gladisch
 * @author Mihai Herda
 */
package gentest;
import dynacode.DynaCode;
import genmethod.GeneratedMethodHelper;
import genmethod.GeneratedMethodReturnObject;
import genmethod.IGeneratedMethod;
import helperfunctions.HelperFunctions;
import java.util.ArrayList;
import java.util.HashMap;
public class GeneratedTest implements IGeneratedTest { 
private static HashMap<String, ArrayList<Integer>> varTraces = new HashMap<String, ArrayList<Integer>>();
IGeneratedMethod generatedMethod = GeneratedMethodHelper.getGeneratedMethod();

 public GeneratedTest(){}

public HashMap<String, ArrayList<Integer>> callGeneratedTest(){
   GeneratedTest testSuiteObject;
   testSuiteObject=new GeneratedTest ();

   testSuiteObject.testcode0();
   testSuiteObject.testcode1();
   testSuiteObject.testcode2();
   testSuiteObject.testcode3();
   testSuiteObject.testcode4();
    return varTraces;
 }

  //Test Case for NodeNr: 371
 public void  testcode0(){
   //Test preamble: creating objects and intializing test data
   int a = (int)0;
   int b = (int)32;
   boolean measuredByEmpty = (boolean)true;
   int i_0 = (int)0;

   //Other variables

   //Calling the method under test   
   ArrayList<Integer> inputVars = new ArrayList<Integer>();
   inputVars.add(b);
   inputVars.add(r_0);
   HashMap<String, ArrayList<Integer>> traces = generatedMethod.callGeneratedMethod(inputVars);
   varTraces = HelperFunctions.mergeMapsKeyWise(varTraces, traces);
 }

  //Test Case for NodeNr: 355
 public void  testcode1(){
   //Test preamble: creating objects and intializing test data
   int a = (int)0;
   int b = (int)3;
   boolean measuredByEmpty = (boolean)true;
   int i_0 = (int)0;

   //Other variables

   //Calling the method under test   
   ArrayList<Integer> inputVars = new ArrayList<Integer>();
   inputVars.add(b);
   inputVars.add(r_0);
   HashMap<String, ArrayList<Integer>> traces = generatedMethod.callGeneratedMethod(inputVars);
   varTraces = HelperFunctions.mergeMapsKeyWise(varTraces, traces);
 }

  //Test Case for NodeNr: 309
 public void  testcode2(){
   //Test preamble: creating objects and intializing test data
   int a = (int)0;
   int b = (int)2;
   boolean measuredByEmpty = (boolean)true;
   int i_0 = (int)0;

   //Other variables

   //Calling the method under test   
   ArrayList<Integer> inputVars = new ArrayList<Integer>();
   inputVars.add(b);
   inputVars.add(r_0);
   HashMap<String, ArrayList<Integer>> traces = generatedMethod.callGeneratedMethod(inputVars);
   varTraces = HelperFunctions.mergeMapsKeyWise(varTraces, traces);
 }

  //Test Case for NodeNr: 263
 public void  testcode3(){
   //Test preamble: creating objects and intializing test data
   int a = (int)0;
   int b = (int)1;
   boolean measuredByEmpty = (boolean)true;
   int i_0 = (int)0;

   //Other variables

   //Calling the method under test   
   ArrayList<Integer> inputVars = new ArrayList<Integer>();
   inputVars.add(b);
   inputVars.add(r_0);
   HashMap<String, ArrayList<Integer>> traces = generatedMethod.callGeneratedMethod(inputVars);
   varTraces = HelperFunctions.mergeMapsKeyWise(varTraces, traces);
 }

  //Test Case for NodeNr: 218
 public void  testcode4(){
   //Test preamble: creating objects and intializing test data
   int a = (int)0;
   int b = (int)0;
   boolean measuredByEmpty = (boolean)true;
   int i_0 = (int)0;

   //Other variables

   //Calling the method under test   
   ArrayList<Integer> inputVars = new ArrayList<Integer>();
   inputVars.add(b);
   inputVars.add(r_0);
   HashMap<String, ArrayList<Integer>> traces = generatedMethod.callGeneratedMethod(inputVars);
   varTraces = HelperFunctions.mergeMapsKeyWise(varTraces, traces);
 }


}