/** This is a test driver generated by KeY 2.7 (internal: 90bb886cd7b78027c8f6703803461f09e5699bb9) (www.key-project.org). 
 * Possible use cases:
 *  Use Case 1. Using JUnit 4:
 *        javac -cp .:PATH_TO_JUNIT4_JAR *.java
 *        java  -cp .:PATH_TO_JUNIT4_JAR:PATH_TO_HAMCREST_JAR org.junit.runner.JUnitCore GenTest
 *  Use Case 2. Use JML runtime checker: 
 *      Compile this file and and execute the main method with a JML runtime checker. On linux you can use the built-in scripts:
 *        ./compileWithOpenJML.sh
 *        ./executeWithOpenJML.sh GenTest
 *  Use Case 3. Use simply a program debugger to follow and understand the execution of the program.
 * @author Christoph Gladisch
 * @author Mihai Herda
 */
package gentest;
import dynacode.DynaCode;
import geninstrument.GenInstrumentHelper;
import geninstrument.IGenInstrument;
import helperfunctions.HelperFunctions;
import java.util.ArrayList;
import java.util.HashMap;
public class GenTest implements IGenTest { 
private static HashMap<String, ArrayList<Integer>> varTraces = new HashMap<String, ArrayList<Integer>>();
IGenInstrument genInstrument = GenInstrumentHelper.getGenInstrument();

 public GenTest(){}

public HashMap<String, ArrayList<Integer>> callGenTest(){
   GenTest testSuiteObject;
   testSuiteObject=new GenTest ();

   testSuiteObject.testcode0();
   testSuiteObject.testcode1();
   testSuiteObject.testcode2();
   testSuiteObject.testcode3();
   testSuiteObject.testcode4();
   testSuiteObject.testcode5();
   testSuiteObject.testcode6();
   testSuiteObject.testcode7();
   testSuiteObject.testcode8();
   testSuiteObject.testcode9();
   testSuiteObject.testcode10();
   testSuiteObject.testcode11();
   testSuiteObject.testcode12();
   testSuiteObject.testcode13();
   testSuiteObject.testcode14();
    return varTraces;
 }

  //Test Case for NodeNr: 2165
 public void  testcode0(){
   //Test preamble: creating objects and intializing test data
   boolean measuredByEmpty = (boolean)true;
   int n = (int)10;

   //Other variables

   /*@ nullable */ int result = 0;
   /*@ nullable */ java.lang.Throwable exc = null;
   //Calling the method under test   
   ArrayList<Integer> inputVars = new ArrayList<Integer>();
   inputVars.add(n);
   HashMap<String, ArrayList<Integer>> traces = genInstrument.callGenInstrument(inputVars);
   varTraces = HelperFunctions.mergeMapsKeyWise(varTraces, traces);
 }

  //Test Case for NodeNr: 2421
 public void  testcode1(){
   //Test preamble: creating objects and intializing test data
   boolean measuredByEmpty = (boolean)true;
   int n = (int)64;

   //Other variables

   /*@ nullable */ int result = 0;
   /*@ nullable */ java.lang.Throwable exc = null;
   //Calling the method under test   
   ArrayList<Integer> inputVars = new ArrayList<Integer>();
   inputVars.add(n);
   HashMap<String, ArrayList<Integer>> traces = genInstrument.callGenInstrument(inputVars);
   varTraces = HelperFunctions.mergeMapsKeyWise(varTraces, traces);
 }

  //Test Case for NodeNr: 1592
 public void  testcode2(){
   //Test preamble: creating objects and intializing test data
   boolean measuredByEmpty = (boolean)true;
   int n = (int)7;

   //Other variables

   /*@ nullable */ int result = 0;
   /*@ nullable */ java.lang.Throwable exc = null;
   //Calling the method under test   
   ArrayList<Integer> inputVars = new ArrayList<Integer>();
   inputVars.add(n);
   HashMap<String, ArrayList<Integer>> traces = genInstrument.callGenInstrument(inputVars);
   varTraces = HelperFunctions.mergeMapsKeyWise(varTraces, traces);
 }

  //Test Case for NodeNr: 2009
 public void  testcode3(){
   //Test preamble: creating objects and intializing test data
   boolean measuredByEmpty = (boolean)true;
   int n = (int)9;

   //Other variables

   /*@ nullable */ int result = 0;
   /*@ nullable */ java.lang.Throwable exc = null;
   //Calling the method under test   
   ArrayList<Integer> inputVars = new ArrayList<Integer>();
   inputVars.add(n);
   HashMap<String, ArrayList<Integer>> traces = genInstrument.callGenInstrument(inputVars);
   varTraces = HelperFunctions.mergeMapsKeyWise(varTraces, traces);
 }

  //Test Case for NodeNr: 2363
 public void  testcode4(){
   //Test preamble: creating objects and intializing test data
   boolean measuredByEmpty = (boolean)true;
   int n = (int)12;

   //Other variables

   /*@ nullable */ int result = 0;
   /*@ nullable */ java.lang.Throwable exc = null;
   //Calling the method under test   
   ArrayList<Integer> inputVars = new ArrayList<Integer>();
   inputVars.add(n);
   HashMap<String, ArrayList<Integer>> traces = genInstrument.callGenInstrument(inputVars);
   varTraces = HelperFunctions.mergeMapsKeyWise(varTraces, traces);
 }

  //Test Case for NodeNr: 2406
 public void  testcode5(){
   //Test preamble: creating objects and intializing test data
   boolean measuredByEmpty = (boolean)true;
   int n = (int)13;

   //Other variables

   /*@ nullable */ int result = 0;
   /*@ nullable */ java.lang.Throwable exc = null;
   //Calling the method under test   
   ArrayList<Integer> inputVars = new ArrayList<Integer>();
   inputVars.add(n);
   HashMap<String, ArrayList<Integer>> traces = genInstrument.callGenInstrument(inputVars);
   varTraces = HelperFunctions.mergeMapsKeyWise(varTraces, traces);
 }

  //Test Case for NodeNr: 1819
 public void  testcode6(){
   //Test preamble: creating objects and intializing test data
   boolean measuredByEmpty = (boolean)true;
   int n = (int)8;

   //Other variables

   /*@ nullable */ int result = 0;
   /*@ nullable */ java.lang.Throwable exc = null;
   //Calling the method under test   
   ArrayList<Integer> inputVars = new ArrayList<Integer>();
   inputVars.add(n);
   HashMap<String, ArrayList<Integer>> traces = genInstrument.callGenInstrument(inputVars);
   varTraces = HelperFunctions.mergeMapsKeyWise(varTraces, traces);
 }

  //Test Case for NodeNr: 2283
 public void  testcode7(){
   //Test preamble: creating objects and intializing test data
   boolean measuredByEmpty = (boolean)true;
   int n = (int)11;

   //Other variables

   /*@ nullable */ int result = 0;
   /*@ nullable */ java.lang.Throwable exc = null;
   //Calling the method under test   
   ArrayList<Integer> inputVars = new ArrayList<Integer>();
   inputVars.add(n);
   HashMap<String, ArrayList<Integer>> traces = genInstrument.callGenInstrument(inputVars);
   varTraces = HelperFunctions.mergeMapsKeyWise(varTraces, traces);
 }

  //Test Case for NodeNr: 1325
 public void  testcode8(){
   //Test preamble: creating objects and intializing test data
   boolean measuredByEmpty = (boolean)true;
   int n = (int)6;

   //Other variables

   /*@ nullable */ int result = 0;
   /*@ nullable */ java.lang.Throwable exc = null;
   //Calling the method under test   
   ArrayList<Integer> inputVars = new ArrayList<Integer>();
   inputVars.add(n);
   HashMap<String, ArrayList<Integer>> traces = genInstrument.callGenInstrument(inputVars);
   varTraces = HelperFunctions.mergeMapsKeyWise(varTraces, traces);
 }

  //Test Case for NodeNr: 764
 public void  testcode9(){
   //Test preamble: creating objects and intializing test data
   boolean measuredByEmpty = (boolean)true;
   int n = (int)4;

   //Other variables

   /*@ nullable */ int result = 0;
   /*@ nullable */ java.lang.Throwable exc = null;
   //Calling the method under test   
   ArrayList<Integer> inputVars = new ArrayList<Integer>();
   inputVars.add(n);
   HashMap<String, ArrayList<Integer>> traces = genInstrument.callGenInstrument(inputVars);
   varTraces = HelperFunctions.mergeMapsKeyWise(varTraces, traces);
 }

  //Test Case for NodeNr: 1026
 public void  testcode10(){
   //Test preamble: creating objects and intializing test data
   boolean measuredByEmpty = (boolean)true;
   int n = (int)5;

   //Other variables

   /*@ nullable */ int result = 0;
   /*@ nullable */ java.lang.Throwable exc = null;
   //Calling the method under test   
   ArrayList<Integer> inputVars = new ArrayList<Integer>();
   inputVars.add(n);
   HashMap<String, ArrayList<Integer>> traces = genInstrument.callGenInstrument(inputVars);
   varTraces = HelperFunctions.mergeMapsKeyWise(varTraces, traces);
 }

  //Test Case for NodeNr: 539
 public void  testcode11(){
   //Test preamble: creating objects and intializing test data
   boolean measuredByEmpty = (boolean)true;
   int n = (int)3;

   //Other variables

   /*@ nullable */ int result = 0;
   /*@ nullable */ java.lang.Throwable exc = null;
   //Calling the method under test   
   ArrayList<Integer> inputVars = new ArrayList<Integer>();
   inputVars.add(n);
   HashMap<String, ArrayList<Integer>> traces = genInstrument.callGenInstrument(inputVars);
   varTraces = HelperFunctions.mergeMapsKeyWise(varTraces, traces);
 }

  //Test Case for NodeNr: 84
 public void  testcode12(){
   //Test preamble: creating objects and intializing test data
   boolean measuredByEmpty = (boolean)true;
   int n = (int)0;

   //Other variables

   /*@ nullable */ int result = 0;
   /*@ nullable */ java.lang.Throwable exc = null;
   //Calling the method under test   
   ArrayList<Integer> inputVars = new ArrayList<Integer>();
   inputVars.add(n);
   HashMap<String, ArrayList<Integer>> traces = genInstrument.callGenInstrument(inputVars);
   varTraces = HelperFunctions.mergeMapsKeyWise(varTraces, traces);
 }

  //Test Case for NodeNr: 351
 public void  testcode13(){
   //Test preamble: creating objects and intializing test data
   boolean measuredByEmpty = (boolean)true;
   int n = (int)2;

   //Other variables

   /*@ nullable */ int result = 0;
   /*@ nullable */ java.lang.Throwable exc = null;
   //Calling the method under test   
   ArrayList<Integer> inputVars = new ArrayList<Integer>();
   inputVars.add(n);
   HashMap<String, ArrayList<Integer>> traces = genInstrument.callGenInstrument(inputVars);
   varTraces = HelperFunctions.mergeMapsKeyWise(varTraces, traces);
 }

  //Test Case for NodeNr: 200
 public void  testcode14(){
   //Test preamble: creating objects and intializing test data
   boolean measuredByEmpty = (boolean)true;
   int n = (int)1;

   //Other variables

   /*@ nullable */ int result = 0;
   /*@ nullable */ java.lang.Throwable exc = null;
   //Calling the method under test   
   ArrayList<Integer> inputVars = new ArrayList<Integer>();
   inputVars.add(n);
   HashMap<String, ArrayList<Integer>> traces = genInstrument.callGenInstrument(inputVars);
   varTraces = HelperFunctions.mergeMapsKeyWise(varTraces, traces);
 }


}