
//----------------------------------------------------
// The following code was generated by CUP v0.12joho 20110608
// Wed May 30 16:23:40 CEST 2012
//----------------------------------------------------

package de.uni_freiburg.informatik.ultimate.smtinterpol.dimacs;

/** CUP generated class containing symbol constants. */
public class LexerSymbols {
  /* terminals */
  public static final int error = 0;
  public static final int EOF = 1;
  public static final int PROBLEM = 2;
  public static final int CNF = 3;
  public static final int NOT = 4;
  public static final int EOC = 5;
  public static final int NUMBER = 6;
}

