package recoder;

public interface TuningParameters {
    int INITIAL_CROSS_REFERENCER_ELEMENT2REFERENCE_HASH_SET_SIZE = 4;

    int INITIAL_SOURCE_INFO_NAME2PRIMITIVE_HASH_SET_SIZE = 64;

    int INITIAL_SOURCE_INFO_REFERENCE2ELEMENT_HASH_SET_SIZE = 1024;
}
